name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.2
  device_info: ^2.0.0
  dio: 4.0.0-beta5
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0-nullsafety.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  get_it: ^6.0.0
  injectable: ^1.2.0
  json_serializable: ^4.0.2
  mockito: ^5.0.0
  moor: ^4.1.0
  moor_db_viewer: ^3.0.0
  moor_inspector: ^0.2.0
  niddler_dart: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  retrofit: ^1.3.4+1
  scroll_when_needed: ^2.0.0
  shared_preferences: ^2.0.3

dev_dependencies:
  build_runner: ^1.11.5
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  icapps_license: ^1.1.0
  icapps_translations: ^4.0.0
  injectable_generator: ^1.2.0
  model_generator: ^4.0.0
  moor_generator: ^4.1.0
  retrofit_generator:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: generator

dependency_overrides:
  analyzer: 1.1.0
  pub_semver: 2.0.0
  retrofit:
    git:
      url: https://github.com/Chimerapps/retrofit.dart
      ref: feature/nullabilitysafe
      path: annotation

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf

icapps_translations:
  api_key: 'lIWZxNlOz3d461rVMeh3dw' #TODO Update this to the correct api key
  default_language: 'nl'
  languages: ['nl','en']
